name: IPTV Auto Build

on:
  schedule:
    - cron: "0 0 * * 1"  # 每周一
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run scripts
        run: |
          python txt_to_json.py
          python json_to_m3u.py

      - name: Commit
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "auto update"
          git push
